import { useState } from 'react'
import { useCartStore } from '@/stores/cartStore'
import { useAuth } from '@/hooks/useAuth'
import { useMutation } from '@tanstack/react-query'
import { supabase } from '@/lib/supabaseClient'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useToast } from '@/components/ui/use-toast'
import { FileText, Loader2 } from 'lucide-react'
import { formatPrice } from '@/lib/utils'

interface OrderRequestModalProps {
  open: boolean
  onClose: () => void
  onSuccess: (orderId?: number) => void
}

export function OrderRequestModal({
  open,
  onClose,
  onSuccess,
}: OrderRequestModalProps) {
  const { items, getTotal, clearCart } = useCartStore()
  const { user, profile, company } = useAuth()
  const { toast } = useToast()
  const [notes, setNotes] = useState('')

  const quoteMutation = useMutation({
    mutationFn: async () => {
      const isDevMode = import.meta.env.VITE_DEV_MODE === 'true'
      const devUserId = isDevMode ? 'dev-user-123' : null
      
      // In dev mode, allow quote creation without auth
      const userId = user?.id || devUserId
      if (!userId) {
        throw new Error('User not authenticated')
      }

      const total = getTotal()
      
      // Prepare order items
      const orderItems = items.map((item) => ({
        product_id: item.product.id.toString(),
        product_name: item.product.name || 'Unnamed Product',
        sku: item.product.sku,
        quantity: item.quantity,
        unit_price: item.price,
        total: item.total,
      }))

      // Create order in database
      // order_number will be auto-generated by the database sequence
      const { data, error } = await supabase
        .from('quotes')
        .insert({
          user_id: userId,
          company_name: company?.name || profile?.full_name || 'Unknown Company',
          email: user?.email || profile?.email || 'dev@example.com',
          phone: null, // Can be added later
          notes: notes.trim() || null,
          items: orderItems,
          total: total,
          status: 'new',
          // order_number will be auto-generated by database default
        })
        .select()
        .single()

      if (error) throw error
      return data
    },
    onSuccess: (data) => {
      toast({
        title: 'Order submitted successfully! 🎉',
        description: `Your order #${data.order_number} has been submitted. We'll process it shortly.`,
      })
      clearCart()
      setNotes('')
      onSuccess(data.id)
      onClose()
    },
    onError: (error) => {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to submit order',
        variant: 'destructive',
      })
    },
  })

  const total = getTotal()
  const companyName = company?.name || profile?.full_name || 'Your Company'
  const userEmail = user?.email || profile?.email || ''

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Submit Order
          </DialogTitle>
          <DialogDescription>
            Review your order details and submit. We'll process it shortly.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 mt-4">
          {/* Company Info */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="company-name">Company Name</Label>
              <Input
                id="company-name"
                value={companyName}
                disabled
                className="bg-muted"
              />
            </div>
            <div>
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                value={userEmail}
                disabled
                className="bg-muted"
              />
            </div>
          </div>

          {/* Notes */}
          <div>
            <Label htmlFor="notes">Additional Notes (Optional)</Label>
            <Textarea
              id="notes"
              placeholder="Any special requirements, delivery dates, or questions..."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={4}
              className="mt-2"
            />
          </div>

          {/* Cart Items Summary */}
          <div>
            <Label className="mb-3 block">Order Items</Label>
            <div className="border rounded-lg divide-y">
              {items.map((item) => {
                const product = item.product
                const image = product.main_image || product.images?.[0]

                return (
                  <div key={product.id} className="p-4 flex items-center gap-4">
                    {image && (
                      <img
                        src={image}
                        alt={product.name || 'Product'}
                        className="w-16 h-16 rounded object-cover flex-shrink-0"
                      />
                    )}
                    <div className="flex-1 min-w-0">
                      <h4 className="font-semibold text-sm line-clamp-1">
                        {product.name || 'Unnamed Product'}
                      </h4>
                      <p className="text-xs text-muted-foreground font-mono">
                        SKU: {product.sku}
                      </p>
                    </div>
                    <div className="text-right flex-shrink-0">
                      <div className="text-sm text-muted-foreground">
                        {item.quantity} × {formatPrice(item.price)}
                      </div>
                      <div className="font-bold">
                        {formatPrice(item.total)}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Total */}
          <div className="flex items-center justify-between text-lg font-bold pt-4 border-t">
            <span>Total Amount</span>
            <span className="text-2xl text-primary">{formatPrice(total)}</span>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button
              variant="outline"
              onClick={onClose}
              className="flex-1"
              disabled={quoteMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              onClick={() => quoteMutation.mutate()}
              disabled={quoteMutation.isPending}
              className="flex-1"
            >
              {quoteMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Submitting...
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4 mr-2" />
                  Submit Order
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

