import { useState } from 'react'
import { useCartStore } from '@/stores/cartStore'
import { useAuth } from '@/hooks/useAuth'
import { useCommissionRate } from '@/hooks/useCommissionRate'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase/client'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useToast } from '@/components/ui/use-toast'
import { FileText, Loader2, Warehouse, Truck, Package, Store, Percent } from 'lucide-react'
import { formatPrice } from '@/lib/utils'
import { ShippingMethod, SHIPPING_METHOD_CONFIG } from '@/types'
import { cn } from '@/lib/utils'
import { useTenant } from '@/lib/tenant/TenantProvider'
import { sendNotification } from '@/lib/notifications'

interface OrderRequestModalProps {
  open: boolean
  onClose: () => void
  onSuccess: (orderId?: number) => void
}

export function OrderRequestModal({
  open,
  onClose,
  onSuccess,
}: OrderRequestModalProps) {
  const { items, getTotal, clearCart } = useCartStore()
  const { user, profile, company } = useAuth()
  const { hasDiscount, commissionRate } = useCommissionRate()
  const { tenant } = useTenant()
  const tenantId = tenant?.id
  const { toast } = useToast()
  const queryClient = useQueryClient()
  const [notes, setNotes] = useState('')
  const [shippingMethod, setShippingMethod] = useState<ShippingMethod>('shop_delivery')

  const quoteMutation = useMutation({
    mutationFn: async () => {
      if (!tenantId) {
        throw new Error('Missing tenant context')
      }
      const isDevMode = import.meta.env.VITE_DEV_MODE === 'true'
      const devUserId = isDevMode ? 'dev-user-123' : null
      
      // In dev mode, allow quote creation without auth
      const userId = user?.id || devUserId
      if (!userId) {
        throw new Error('User not authenticated')
      }

      const total = getTotal()
      
      // Prepare order items
      const orderItems = items.map((item) => ({
        product_id: item.product.id.toString(),
        product_name: item.product.name || 'Unnamed Product',
        sku: item.product.sku,
        quantity: item.quantity,
        unit_price: item.price,
        total: item.total,
      }))

      // Create order in database
      // order_number will be auto-generated by the database sequence
      const { data, error } = await supabase
        .from('quotes')
        .insert({
          tenant_id: tenantId,
          user_id: userId,
          company_name: company?.name || profile?.full_name || 'Unknown Company',
          email: user?.email || profile?.email || 'dev@example.com',
          phone: null, // Can be added later
          notes: notes.trim() || null,
          items: orderItems,
          total: total,
          status: 'new',
          shipping_method: shippingMethod || 'shop_delivery',
          // order_number will be auto-generated by database default
        })
        .select()
        .single()

      if (error) {
        console.error('Error creating order:', error)
        // Provide helpful error message if column doesn't exist
        if (error.message?.includes('shipping_method') || error.message?.includes('column') || error.code === 'PGRST116') {
          throw new Error('Database migration required: The shipping_method column does not exist. Please run the SQL migration: supabase/add-shipping-method-column.sql')
        }
        throw error
      }
      return data
    },
    onSuccess: (data) => {
      // Invalidate orders query to refresh the orders list
      const isDevMode = import.meta.env.VITE_DEV_MODE === 'true'
      const devUserId = isDevMode ? 'dev-user-123' : null
      const userId = user?.id || devUserId
      queryClient.invalidateQueries({ queryKey: ['tenant', tenantId, 'orders', userId] })
      queryClient.invalidateQueries({ queryKey: ['tenant', tenantId, 'orders'] })

      // Notify admins about the new order
      sendNotification({
        type: 'order_created',
        entityType: 'quotes',
        entityId: String(data.id),
        metadata: {
          order_number: data.order_number,
          company_name: company?.name || profile?.full_name || 'Unknown',
        },
        targetAudience: 'admins',
      })
      
      toast({
        title: 'Order submitted successfully! 🎉',
        description: `Your order #${data.order_number} has been submitted. We'll process it shortly.`,
      })
      clearCart()
      setNotes('')
      setShippingMethod('shop_delivery')
      onSuccess(data.id)
      onClose()
    },
    onError: (error) => {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to submit order',
        variant: 'destructive',
      })
    },
  })

  const total = getTotal()
  const companyName = company?.name || profile?.full_name || 'Your Company'
  const userEmail = user?.email || profile?.email || ''

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Submit Order
          </DialogTitle>
          <DialogDescription>
            Review your order details and submit. We'll process it shortly.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 mt-4">
          {/* Company Info */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label htmlFor="company-name">Company Name</Label>
              <Input
                id="company-name"
                value={companyName}
                disabled
                className="bg-muted"
              />
            </div>
            <div>
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                value={userEmail}
                disabled
                className="bg-muted"
              />
            </div>
          </div>

          {/* Shipping Method Selection */}
          <div>
            <Label className="mb-3 block">Shipping Method *</Label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {(['shop_delivery', 'warehouse_pickup', 'transport_company', 'dropshipping'] as ShippingMethod[]).map((method) => {
                const config = SHIPPING_METHOD_CONFIG[method]
                const isSelected = shippingMethod === method
                const IconComponent = method === 'warehouse_pickup' ? Warehouse 
                  : method === 'transport_company' ? Truck 
                  : method === 'dropshipping' ? Package 
                  : Store

                return (
                  <button
                    key={method}
                    type="button"
                    onClick={() => setShippingMethod(method)}
                    className={cn(
                      'flex items-center gap-3 p-4 rounded-lg border-2 transition-all text-left',
                      isSelected
                        ? 'border-primary bg-primary/5 ring-2 ring-primary/20'
                        : 'border-muted hover:border-muted-foreground/30 hover:bg-muted/50'
                    )}
                  >
                    <div className={cn(
                      'p-2 rounded-lg',
                      isSelected ? 'bg-primary/10' : 'bg-muted'
                    )}>
                      <IconComponent className={cn(
                        'w-5 h-5',
                        isSelected ? 'text-primary' : 'text-muted-foreground'
                      )} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className={cn(
                        'font-medium text-sm',
                        isSelected ? 'text-primary' : 'text-foreground'
                      )}>
                        {config.shortLabel}
                      </p>
                      <p className="text-xs text-muted-foreground truncate">
                        {config.label}
                      </p>
                    </div>
                    {isSelected && (
                      <div className="w-2 h-2 rounded-full bg-primary" />
                    )}
                  </button>
                )
              })}
            </div>
          </div>

          {/* Notes */}
          <div>
            <Label htmlFor="notes">Additional Notes (Optional)</Label>
            <Textarea
              id="notes"
              placeholder="Any special requirements, delivery dates, or questions..."
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={4}
              className="mt-2"
            />
          </div>

          {/* Cart Items Summary */}
          <div>
            <Label className="mb-3 block">Order Items</Label>
            <div className="border rounded-lg divide-y">
              {items.map((item) => {
                const product = item.product
                const image = product.main_image || product.images?.[0]

                return (
                  <div key={product.id} className="p-4 flex items-center gap-4">
                    {image && (
                      <img
                        src={image}
                        alt={product.name || 'Product'}
                        className="w-16 h-16 rounded object-cover flex-shrink-0"
                      />
                    )}
                    <div className="flex-1 min-w-0">
                      <h4 className="font-semibold text-sm line-clamp-1">
                        {product.name || 'Unnamed Product'}
                      </h4>
                      <p className="text-xs text-muted-foreground font-mono">
                        SKU: {product.sku}
                      </p>
                    </div>
                    <div className="text-right flex-shrink-0">
                      <div className="text-sm text-muted-foreground">
                        {item.quantity} × {formatPrice(item.price)}
                      </div>
                      <div className="font-bold">
                        {formatPrice(item.total)}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Discount Banner */}
          {hasDiscount && (
            <div className="flex items-center gap-2 p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <Percent className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
              <div>
                <p className="font-medium text-emerald-700 dark:text-emerald-300">
                  Your {Math.round(commissionRate * 100)}% discount is applied
                </p>
                <p className="text-xs text-emerald-600/80 dark:text-emerald-400/80">
                  Commission discount applied to all items
                </p>
              </div>
            </div>
          )}

          {/* Total */}
          <div className="flex items-center justify-between text-lg font-bold pt-4 border-t">
            <span>Total Amount</span>
            <div className="text-right">
              <span className="text-2xl text-primary">{formatPrice(total)}</span>
              {hasDiscount && (
                <Badge 
                  variant="secondary" 
                  className="ml-2 gap-1 px-2 py-0.5 text-xs font-semibold bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-500/20"
                >
                  <Percent className="w-3 h-3" />
                  {Math.round(commissionRate * 100)}% OFF
                </Badge>
              )}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button
              variant="outline"
              onClick={onClose}
              className="flex-1"
              disabled={quoteMutation.isPending}
            >
              Cancel
            </Button>
            <Button
              onClick={() => quoteMutation.mutate()}
              disabled={quoteMutation.isPending}
              className="flex-1"
            >
              {quoteMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Submitting...
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4 mr-2" />
                  Submit Order
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
